image:
  repository: ghcr.io/headinthecloudsolutions/kadense
  tag: latest

jupyternetes:
  pods:
    operator:
      enabled: true
      image:
        repository: ""
        name: jupyternetes-pods-operator
        tag: ""
        pullPolicy: Always
      serviceAccount:
        create: true
        name: ""
      nodeSelector: {}
      tolerations: []
      affinity: {}
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  pvcs:
    operator:
      enabled: true
      image:
        repository: ""
        name: jupyternetes-pvcs-operator
        tag: ""
        pullPolicy: Always
      serviceAccount:
        create: true
        name: ""
      nodeSelector: {}
      tolerations: []
      affinity: {}
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  template:
    name: default-template
    spec:
      pods:
      - name: notebook
        labels:
          jupyternetes.kadense.io/userId: '{jupyterhub.user.id}'
        spec:
          containers:
          - name: notebook
            image: quay.io/jupyter/datascience-notebook:latest
            volumeMounts:
            - name: workspace-pvc
              mountPath: /home/jovyan/work
          volumes:
          - name: workspace-pvc
            persistentVolumeClaim:
              claimName: '{jupyternetes.pvcs.workspace}'
      pvcs:
      - name: workspace
        labels:
          jupyternetes.kadense.io/userId: '{jupyterhub.user.id}'
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi    