on:
    workflow_call:
      inputs:
          GitVersion_SemVer:
              description: 'The semantic version of the project'
              required: true
              type: string

          Config:
              description: 'The configuration for the workflow'
              required: true
              type: string

jobs:
  build:
    name: Build Python distribution 
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ${{ fromJson(inputs.Config).python.versions }}
            module: ${{ fromJson(inputs.Config).python.modules }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install pypa/build
      run: >-
        python3 -m pip install build --user

    - name: Set Version 
      working-directory: python/${{ matrix.module }}
      run: echo "__version__ = \"${{ inputs.GitVersion_SemVer }}\"" > ./${{ matrix.module }}/_version.py

    - name: Build a binary wheel and a source tarball
      working-directory: python/${{ matrix.module }}
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distribution-${{ matrix.module }}-${{ matrix.python-version }}
        path: python/${{ matrix.module }}/dist/
