name: Create Release Packages

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

permissions:
  packages: write
  contents: read

jobs:
  semver:
    uses: headinthecloudsolutions/kadense/.github/workflows/container-images.yaml@main
    secrets: inherit 
    with:
      images: |
        [
          "jupyternetes-pods-operator",
          "jupyternetes-pvcs-operator"
        ]