name: Create Release Packages

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

permissions:
  packages: write
  contents: write

jobs:
  get-version:
    uses: headinthecloudsolutions/kadense/.github/workflows/semver.yaml@main
    secrets: inherit 
  
  publish-helm-chart:
    uses: headinthecloudsolutions/kadense/.github/workflows/publish-helm-chart.yaml@main
    secrets: inherit
    needs:
    - get-version
    with:
      GitVersion_SemVer: ${{ needs.get-version.outputs.GitVersion_SemVer }}
  
  # container-images:
  #   uses: headinthecloudsolutions/kadense/.github/workflows/container-images.yaml@main
  #   needs: 
  #   - get-version
  #   secrets: inherit 
  #   with:
  #     GitVersion_SemVer: ${{ needs.get-version.outputs.GitVersion_SemVer }} 
        