on:
    workflow_call:
        outputs:
            GitVersion_SemVer:
                description: 'The semantic version of the project'
                value: '${{ jobs.get-version.outputs.GitVersion_SemVer }}'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      GitVersion_SemVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id: gitversion
      with:
        useConfigFile: true
  